---
label: Products
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: photo
  type: file
  config:
    maxSize: 2
  label: Photo
- name: model_number
  type: text
  config:
    required: false
  label: Model Number
- name: msrp
  type: text
  config:
    required: false
  label: MSRP
pages:
- content/products/20kw-7038-wifi-enabled.md
- content/products/powerpact-6998-8-circuit-switch.md
